### ISSUE TITLE
add support for directives

### ISSUE THREAD

**Issue by chlegou** [codehint-ng/ng-controls#1]
Hi there,  

i'm having issues using this library when parsing html that contains directives.

my issue is similar to this:   https://stackoverflow.com/questions/46217049/angular-2-how-can-i-apply-directives-to-sanitized-html-innerhtml

here is the error i'm getting:

    Can't bind to 'imgdialog' since it isn't a known property of 'img'. ("'><img style='max-height: 250px' src='https://link.com/123.png' alt='help-fb-req' [ERROR ->][imgdialog]></div>"): 

I have tried including imports of the directives, but it didn't worked. i have got the same error above.

i hope you look for it.

**UPDATE**

... it actually worked, when passing directive name like that `<img imgdialog>` and throwing error when passing it like that:  `<img [imgdialog]='01254'>`

Thanks.

**Comment by mazhekin** [comment]
Hi, I have add test directive, so it works perfectly, you can check it commit above. So the issue you got, i thick you mistype:
1) incorect:  <img [imgdialog]='01254'>
2) correct: <img [imgdialog]="'01254'"> or <img imgdialog="01254">

**Comment by chlegou** [comment]
Ah you might be right. I haven't paid attention to quotes. But since the error I have got wasn't related to it, I didn't noticed it.  
Thank you! :)
